trigger:
  - master
  - refs/tags/*

pr:
  - master

resources:
  containers:
  - container: snmp
    image: koshh/aiosnmp:latest
    ports:
      - 161:161/udp

jobs:
  - job: check
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          architecture: 'x64'

      - script: pip install mypy==0.812 isort==5.8.0 flake8==3.9.2 black==21.5b1
        displayName: 'Install Dependencies'

      - script: flake8 aiosnmp/ tests/ examples/ setup.py
        displayName: 'Run flake8'

      - script: isort -q --check --diff aiosnmp/ tests/ examples/ setup.py
        displayName: 'Run isort'

      - script: black -l 120 -q --check --diff aiosnmp/ tests/ examples/ setup.py
        displayName: 'Run black'

      - script: mypy aiosnmp/
        displayName: 'Run mypy'

  - job: tests
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        Python36-asyncio:
          python.version: '3.6'
          loop: 'asyncio'
        Python36-uvloop:
          python.version: '3.6'
          loop: 'uvloop'
        Python37-asyncio:
          python.version: '3.7'
          loop: 'asyncio'
        Python37-uvloop:
          python.version: '3.7'
          loop: 'uvloop'
        Python38-asyncio:
          python.version: '3.8'
          loop: 'asyncio'
        Python38-uvloop:
          python.version: '3.8'
          loop: 'uvloop'
        Python39-asyncio:
          python.version: '3.9'
          loop: 'asyncio'
        Python39-uvloop:
          python.version: '3.9'
          loop: 'uvloop'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
        displayName: 'Use Python $(python.version)'

      - script: docker ps
        displayName: 'Docker PS'

      - script: env
        displayName: 'Env'

      - script: pip install pytest==6.2.4 pytest-asyncio==0.15.1 pytest-cov==2.12.0 uvloop==0.15.2 codecov==2.1.11
        displayName: 'Install Dependencies'

      - script: pytest -v --durations=5 --cov=aiosnmp --cov-report=term-missing --event-loop=$(loop)
        displayName: 'Run Tests'

      - script: bash <(curl -s https://codecov.io/bash)
        displayName: 'Upload to codecov.io'

    services:
      snmp: snmp

  - job: twine
    pool:
      vmImage: 'ubuntu-latest'

    dependsOn:
      - check
      - tests
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/'))

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          architecture: 'x64'

      - script: pip install wheel twine
        displayName: 'Install Dependencies'

      - script: python setup.py bdist_wheel
        displayName: 'Build'

      - task: TwineAuthenticate@1
        displayName: 'Twine Authenticate'
        inputs:
          pythonUploadServiceConnection: uploadToPypi

      - script: python -m twine upload -r uploadToPypi --config-file $(PYPIRC_PATH) dist/*
        displayName: 'Upload'
